mybatis:
  type-aliases-package: com.fool3.common.admin.entity
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/common_admin?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

swagger:
  enabled: true